server:
  port: 8081
  shutdown: graceful
  tomcat:
    #url统一编码
    uri-encoding: utf-8
    # 处理的最大并发请求数
    # 在给定时间接受和处理的最大连接数，默认值10000
    max-connections: 20000
    # 初始化时创建的最小线程数，始终保持运行，默认值10
    # 监听端口队列最大数，满了之后客户请求会被拒绝(不能小于maxSpareThreads)，默认为100
    acceptCount: 700
    threads:
      max: 1000
      min-spare: 20

spring:
  datasource:
    druid:
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/blog?useAffectedRows=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEnco
        username: root
        password: 123456
        initialSize: 2
        minIdle: 1
        maxActive: 10
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 600000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        validationQuery: select 1 from dual
        keepAlive: true
        logAbandoned: true
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/blog/law?useAffectedRows=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEnco
        username: blog
        password: blog
        initialSize: 2
        minIdle: 1
        maxActive: 10
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 600000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        validationQuery: select 1 from dual
        keepAlive: true
        logAbandoned: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    database: 0
    lettuce:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0


